services:
  - type: web
    name: traderoad-ai
    env: static
    buildCommand: |
      # Instalación de dependencias
      npm install
      
      # Generar archivo config.js antes del build
      mkdir -p ./public
      node ./scripts/generate-config.js
      
      # Construir la aplicación
      npm run build
      
      # Copiar config.js a dist (por si acaso)
      cp -f ./public/config.js ./dist/config.js 2>/dev/null || :
      
      # Logs para depuración
      echo "Contenido de /dist:"
      ls -la ./dist
      echo "Contenido de /dist/config.js (si existe):"
      cat ./dist/config.js 2>/dev/null || echo "El archivo config.js no existe en dist"
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # La variable que estamos usando actualmente
      - key: VITE_API_KEY
        sync: true # Alternativa para Vite
      - key: GEMINI_API_KEY
        sync: true # Nombre alternativo que podría estar usando la app
      - key: REACT_APP_API_KEY
        sync: true # Nombre alternativo para React
