services:
  - type: web
    name: traderoad-ai
    env: static
    buildCommand: npm install && mkdir -p ./public && node ./scripts/generate-config.js && npm run build && cp -f ./public/config.js ./dist/config.js
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # La variable que estamos usando actualmente
      - key: VITE_API_KEY
        sync: true # Alternativa para Vite
      - key: GEMINI_API_KEY
        sync: true # Nombre alternativo que podría estar usando la app
      - key: REACT_APP_API_KEY
        sync: true # Nombre alternativo para React
