services:
  - type: web
    name: traderoad-ai
    env: node
    buildCommand: |
      # Instalar dependencias del frontend
      npm install
      
      # Verificar si existe el script de configuración
      if [ -f "./scripts/generate-config.cjs" ]; then
        echo "Ejecutando generate-config.cjs"
        node ./scripts/generate-config.cjs
      elif [ -f "./scripts/generate-config.js" ]; then
        echo "Ejecutando generate-config.js"
        node ./scripts/generate-config.js
      else
        echo "No se encontró script de configuración"
      fi
      
      # Mostrar las líneas relevantes de index.html DESPUÉS de la inyección de la API key
      echo "Mostrando sección de script de API Key en index.html DESPUÉS de la inyección:"
      grep -C 15 'const injectedApiKey' index.html || echo "No se encontró la clave 'injectedApiKey'"
      echo "-----------------------------------------------------------------"
      
      # Construir la aplicación frontend
      npm run build
      
      # Listar archivos en dist para asegurarse de que todo está correcto
      echo "Contenido del directorio dist:"
      ls -la ./dist
      
      # Instalar dependencias del servidor
      cd server && npm install
    startCommand: node start.js
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # Compatibilidad con el método anterior
      - key: VITE_API_KEY
        sync: true # Alternativa para Vite
      - key: GEMINI_API_KEY
        sync: true # Esta es la variable que usará el servidor backend
