services:
  - type: web
    name: traderoad-ai
    env: static
    buildCommand: |
      npm install && \
      npm run build && \
      mkdir -p ./dist && \
      node ./scripts/generate-config.js
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # Necesitamos que esté disponible durante el build
