services:
  - type: web
    name: traderoad-ai
    env: static
    buildCommand: |
      # Instalar dependencias
      npm install
      
      # Ejecutar script para inyectar API key en index.html
      node ./scripts/generate-config.js
      
      # Mostrar las líneas relevantes de index.html DESPUÉS de la inyección de la API key
      echo "Mostrando sección de script de API Key en index.html DESPUÉS de la inyección:"
      grep -C 15 'const injectedApiKey' index.html
      echo "-----------------------------------------------------------------"
      
      # Construir la aplicación (Vite se encargará de procesar el index.html modificado)
      npm run build
      
      # Listar archivos en dist para asegurarse de que todo está correcto
      echo "Contenido del directorio dist:"
      ls -la ./dist
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # La variable que estamos usando actualmente
      - key: VITE_API_KEY
        sync: true # Alternativa para Vite
      - key: GEMINI_API_KEY
        sync: true # Nombre alternativo que podría estar usando la app
      - key: REACT_APP_API_KEY
        sync: true # Nombre alternativo para React
