services:
  - type: web
    name: traderoad-ai
    env: node
    buildCommand: |
      # Instalar todas las dependencias con un flag específico para incluir dev
      npm install --include=dev

      # Instalar específicamente las dependencias CSS requeridas
      npm install --no-save autoprefixer@^10.4.21 tailwindcss@^3.4.17 postcss@^8.5.6
      
      # Ejecutar script de configuración para Render
      node render-build-setup.js
      
      # Crear carpeta pública para archivos estáticos
      echo "Creando directorio público para archivos estáticos..."
      mkdir -p ./public/lib
      
      # Verificar si existe el script de configuración y ejecutarlo
      echo "Verificando ubicación del script..."
ls -la ./scripts/
if [ -f "./scripts/generate-config.cjs" ]; then
        echo "Ejecutando generate-config.cjs"
        node "$(pwd)/scripts/generate-config.cjs"
      elif [ -f "./scripts/generate-config.js" ]; then
        echo "Ejecutando generate-config.js"
        node ./scripts/generate-config.js
      else
        echo "No se encontró script de configuración"
      fi
      
      # Mostrar las líneas relevantes de index.html DESPUÉS de la inyección de la API key
      echo "Mostrando sección de script de API Key en index.html DESPUÉS de la inyección:"
      grep -C 15 'const injectedApiKey' index.html || echo "No se encontró la clave 'injectedApiKey'"
      echo "-----------------------------------------------------------------"
      
      # Mostrar todas las dependencias instaladas para diagnóstico
      echo "Listando todas las dependencias instaladas:"
      npm list --depth=0
      
      # Mostrar el contenido del archivo vite.config.ts
      echo "Contenido de vite.config.ts:"
      cat vite.config.ts
      echo "-----------------------------------------------------------------"
      
      # Verificar la estructura del directorio node_modules
      echo "Verificando existencia de plugins críticos:"
      ls -la ./node_modules/@vitejs/plugin-react || echo "Plugin React no encontrado"
      ls -la ./node_modules/@originjs/vite-plugin-commonjs || echo "Plugin CommonJS no encontrado"
      ls -la ./node_modules/vite-plugin-node-polyfills || echo "Plugin Node Polyfills no encontrado"
      
      # Construir la aplicación frontend
      npm run build
      
      # Listar archivos en dist para asegurarse de que todo está correcto
      echo "Contenido del directorio dist:"
      ls -la ./dist
      
      # Instalar dependencias del servidor
      cd server && npm install
    startCommand: node start.cjs
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # Compatibilidad con el método anterior
      - key: VITE_API_KEY
        sync: true # Alternativa para Vite
      - key: GEMINI_API_KEY
        sync: true # Esta es la variable que usará el servidor backend
