services:
  - type: web
    name: traderoad-ai
    env: static
    buildCommand: |
      # Instalar dependencias
      npm install
      
      # Crear directorio public si no existe
      mkdir -p ./public
      
      # Generar archivo config.js
      node ./scripts/generate-config.js
      
      # Mostrar el contenido del config.js generado
      echo "Contenido de config.js generado:"
      cat ./public/config.js
      
      # Construir la aplicación
      npm run build
      
      # Copiar config.js a dist
      cp -f ./public/config.js ./dist/config.js
      
      # Verificar que el archivo se haya copiado correctamente
      echo "Verificando config.js en dist:"
      cat ./dist/config.js
      
      # Listar archivos en dist para asegurarse de que todo está correcto
      echo "Contenido del directorio dist:"
      ls -la ./dist
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: API_KEY
        sync: true # La variable que estamos usando actualmente
      - key: VITE_API_KEY
        sync: true # Alternativa para Vite
      - key: GEMINI_API_KEY
        sync: true # Nombre alternativo que podría estar usando la app
      - key: REACT_APP_API_KEY
        sync: true # Nombre alternativo para React
